# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
#    -   id: fmt
#        args: ["--manifest-path", "rust/Cargo.toml"]
    -   id: cargo-check
        args: ["--manifest-path", "rust/Cargo.toml"]
    -   id: clippy
        args: ["--manifest-path", "rust/Cargo.toml"]

#-   repo: local
#    hooks:
#    -   id: go-unit-tests
#        name: run go test s(go test)
#        language: system
#        entry: bash -c 'cd subdir && exec go test ./...'
#        pass_filenames: false
#        types: [go]
#        files: ^subdir/
